export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-bgcolor text-txtcolor">
        <div className="container mx-auto">
          <div className="mt-10 mb-6 h-12 bg-slate-800">
            header
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
